import type { Task } from "./types";

export const SAMPLE_TASKS: Task[] = [
  {
    id: "t1",
    title: "Investigación sobre elementos HTML",
    description: "Investigación sobre los diferentes elementos HTML y su uso.",
    status: "completada",
    tags: ["#"],
    dueDate: "2025-07-31",
    image: "/images/investigacion.jpg", // <— imagen de la tarea
    attachments: [{ type: "pdf", label: "Documento", url: "/docs/elementos-formulario.pdf" }],
  },
  {
    id: "t2",
    title: "Página Web–Hoja de Vida",
    description: "Portafolio personal.",
    status: "completada",
    tags: ["#React", "#Node", "#javaScript"],
    dueDate: "2025-07-24",
    image: "/images/hoja de vida.jpg",
    attachments: [{ type: "link", label: "Url", url: "https://danielbrn89.github.io/home.html" }],
  },
  {
    id: "t3",
    title: "Glosario",
    description: "Diseñar un glosario de términos.",
    status: "completada",
    tags: ["#"],
    dueDate: "2025-07-18",
    image: "/images/investigacion.jpg",
    attachments: [{ type: "pdf", label: "Documento", url: "/docs/glosario.pdf" }],
  },
  // agrega más tareas con su image:
  {
    id: "t4",
    title: "Diseño Responsive",
    description: "Flujo de diseño adaptable.",
    status: "completada",
    tags: ["#"],
    dueDate: "2025-08-05",
    image: "/images/diseno-responsive.png",
    attachments: [{ type: "link", label: "Página", url: "https://pryecto-dise-o.vercel.app/" }],
  },
  {
    id: "t5",
    title: "Formulario HTML",
    description: "Formulario para solicitud y guardado de datos.",
    status: "completada",
    tags: ["#html", "#CSS", "#javaScript"],
    dueDate: "2025-07-20",
    image: "/images/investigacion.jpg",
    attachments: [{ type: "link", label: "Formulario", url: "https://practica-formulario-omega.vercel.app/" }],
  },
  {
    id: "t6",
    title: "INVESTIGACION HOOKS EN REACT",
    description: "Investigación sobre el uso de Hooks en React.",
    status: "completada",
    tags: ["#React", "#Hooks"],
    dueDate: "2025-07-20",
    image: "/images/hooks-react.png",
    attachments: [{ type: "pdf", label: "Documento", url: "/docs/hooks-react.pdf" }],
  },
];
